apiVersion: apps/v1
kind: Deployment

metadata:
  name: segment3d-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: segment3d-worker

  template:
    metadata:
      labels:
        app: segment3d-worker

    spec:
      containers:
        - name: segment3d-worker
          image: segment3d-worker
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: segment3d-worker-configmap
